### ISSUE TITLE
cascade path instructions

### ISSUE THREAD

**Issue by ghost** [G10DRAS/JasperModules#1]
I am trying to set this up, but I see you said copy the .xml file mentioned to /cascade.  Did you mean /cascade/ to move it into the directory? Or cp it (copy/rename) as a file 'cascade', as instructed.  Also, if you are interested I am going to try to use this to ID people for Jasper. Making it 'know' who you are, and possibly profile switch.  Feel free to contact me matt@mattcurry.com if you are interested in collaborating.

**Comment by G10DRAS** [comment]
Hey Matt, I have updated the instruction. Copy haarcascade_frontalface_default.xml file to ~/jasper/static/cascade directory.

cp haarcascade_frontalface_default.xml ~/jasper/static/cascade/.
